// All interface copy in one place, so the copy lint can check it.
// Numbers are never written here: they are computed from the data and passed in.
import type { Meta } from './types';
import type { Stats } from './data';
import { day, longDate, monthName, shortDate } from './data';

export const copy = {
  title: (meta: Meta) => `${meta.headline}: AI at UNGA81`,
  description: (s: Stats) =>
    `${s.items} events, sessions and launches on AI around the 81st session of the UN General Assembly, and ${s.membersAi} of ${s.members} Member States mentioning AI in the General Debate. Explore every item.`,
  tag: 'UNGA81 HIGH LEVEL WEEK',
  kicker: (meta: Meta) =>
    `${day(meta.window.from)} TO ${day(meta.window.to)} ${monthName(meta.window.to).toUpperCase()} ${meta.window.to.slice(0, 4)}  AS AT ${day(meta.as_at)} ${monthName(meta.as_at).toUpperCase()}`,
  deck1: (s: Stats) => `${s.items} UN linked events, sessions and launches on AI.`,
  deck2: (s: Stats) => `${s.hlw} of them in high level week.`,
  tabs: { floor: 'FLOOR', pulse: 'PULSE', constellation: 'CONSTELLATION', index: 'INDEX' },
  viewNames: { floor: 'Floor', pulse: 'Pulse', constellation: 'Constellation', index: 'Index' },
  filter: 'FILTER',
  clear: 'CLEAR',
  close: 'CLOSE',
  search: 'SEARCH',
  searchPlaceholder: 'Find a country, organisation or event',
  searchGroups: { countries: 'COUNTRIES', organisations: 'ORGANISATIONS', items: 'ITEMS' },
  searchNone: 'Nothing found. Try another spelling.',
  empty: 'No items match these filters. Clear one to see more.',
  seatCaption1: (s: Stats) => `of ${s.members} Member States that spoke from ${day(s.debateFrom)} to ${shortDate(s.debateTo)}`,
  seatCaption2: 'mentioned AI in the General Debate. One seat each.',
  pending: (s: Stats) =>
    s.unverified ? 'Dotted outlines mark statements pending verification against official texts.' : '',
  seatModes: { day: 'BY DAY', group: 'BY REGIONAL GROUP' },
  groupCaption: 'Rows from the outside in, lit seats of seats in each group:',
  legendTitle: 'CONVENED BY',
  marksTitle: 'MARKS',
  facets: { convener: 'CONVENER', platform: 'PLATFORM', theme: 'THEME', where: 'WHERE', type: 'TYPE' },
  facetHeads: { conv: 'CONVENED BY', theme: 'THEME', platform: 'PLATFORM', type: 'TYPE', loc: 'WHERE', d: 'DATES', pga: 'PARTICIPATION' },
  pgaToggle: 'PGA TOOK PART',
  allDates: 'ALL DATES',
  methodLine: (meta: Meta) =>
    `Each mark is one UN linked event, session, launch or official meeting on AI. Status as at ${longDate(meta.as_at)}.`,
  footer: (meta: Meta) => meta.disclaimer,
  credit: 'A Nerd Lab project',
  about: 'ABOUT AND METHOD',
  download: 'Download the dataset (Excel)',
  downloadCsv: 'DOWNLOAD CSV',
  shareItem: 'SHARE THIS ITEM',
  copyCitation: 'COPY CITATION',
  copied: 'COPIED',
  linkCopied: 'LINK COPIED',
  saveImage: 'SAVE IMAGE',
  saving: 'SAVING',
  portrait: '1080 X 1350',
  landscape: '1200 X 627',
  prev: 'PREVIOUS',
  next: 'NEXT',
  source: 'SOURCE',
  transcript: 'TRANSCRIPT',
  statement: 'STATEMENT',
  citation: (meta: Meta) =>
    `Islam, M. (${meta.as_at.slice(0, 4)}). ${meta.headline}: AI at UNGA81. ${meta.site} (as at ${longDate(meta.as_at)})`,
  itemsTab: 'ITEMS',
  statementsTab: 'GENERAL DEBATE',
  cols: {
    date: 'DATE',
    title: 'TITLE',
    conv: 'CONVENER',
    platform: 'PLATFORM',
    type: 'TYPE',
    loc: 'WHERE',
    themes: 'THEMES',
    organisers: 'ORGANISERS',
    source: 'SOURCE',
    order: 'NO.',
    country: 'COUNTRY',
    speaker: 'SPEAKER',
    gist: 'ON AI',
    links: 'LINKS',
  },
  fields: {
    organisers: 'ORGANISERS',
    themes: 'THEMES',
    status: 'STATUS',
    confidence: 'CONFIDENCE',
    detail: 'DETAIL',
    platform: 'PLATFORM',
    type: 'TYPE',
    loc: 'WHERE',
    pga: 'PGA TOOK PART',
    milestone: 'MILESTONE',
  },
  status: { held: 'Held', ongoing: 'Ongoing', scheduled: 'Scheduled', undated: 'Undated' } as Record<string, string>,
  confidence: { official: 'Official listing', reported: 'Reported', mixed: 'Official and reported' } as Record<string, string>,
  countryItems: 'ITEMS IT CONVENED OR CO HOSTED',
  countryStatement: 'GENERAL DEBATE STATEMENT',
  openCountry: 'OPEN THE COUNTRY PAGE',
  noJs: 'The interactive views need JavaScript. The full index of items and statements is below.',
  itemLine: (n: number) => `One of ${n} events, sessions and launches on AI around UNGA81`,
  seeAll: (n: number) => `SEE IT AMONG ALL ${n}`,
  exploreAll: (n: number) => `EXPLORE ALL ${n}`,
  backHome: 'BACK TO THE FULL VIEW',
  statementsIntro: (s: Stats) => `${s.statements} statements in speaking order. The AI column is filled only where the statement mentioned AI.`,
  aboutHeads: {
    method: 'METHOD',
    rules: 'COUNTING RULES',
    categories: 'CATEGORIES',
    sources: 'SOURCES',
    quotes: 'VERIFIED QUOTES',
    author: 'AUTHOR',
    data: 'DATA',
  },
  rules: (s: Stats, meta: Meta) => [
    `${s.items} items in the window from ${shortDate(meta.window.from)} to ${longDate(meta.window.to)}, ${s.hlw} of them in high level week from ${day(meta.high_level_week.from)} to ${shortDate(meta.high_level_week.to)}.`,
    `The busiest day was ${shortDate(s.peakDay)}, with ${s.peak} items.`,
    `${s.statements} General Debate statements, of which ${s.members} were delivered by Member States. ${s.membersAi} of those ${s.members} mentioned AI.`,
    'The Secretary-General, the President of the General Assembly and observers appear in the Index and the country search, not in the seat ring.',
    'Colour always shows the convener. Shape always shows the type of item. A hollow ring means the organiser was not identified.',
  ],
  sourcesText: (n: number) => `Every item links to its source. The items draw on ${n} distinct source websites, listed with the number of items from each.`,
  chartSummary: {
    floor: (s: Stats, meta: Meta) =>
      `Floor view. ${s.items} items are arranged by day around a half circle, from ${shortDate(meta.window.from)} on the left to ${shortDate(meta.window.to)} on the right. Each day is a column of marks. The busiest day is ${shortDate(s.peakDay)} with ${s.peak} items. High level week, ${day(meta.high_level_week.from)} to ${shortDate(meta.high_level_week.to)}, holds ${s.hlw}. Inside the half circle, one seat for each of the ${s.members} Member States that spoke in the General Debate. ${s.membersAi} seats are lit, one for each Member State that mentioned AI.`,
    pulse: (s: Stats, meta: Meta) =>
      `Pulse view. A calendar of ${s.items} items from ${shortDate(meta.window.from)} to ${longDate(meta.window.to)}, one group of marks per day, with milestones labelled and the General Debate seats under ${day(s.debateFrom)} to ${shortDate(s.debateTo)}.`,
    constellation: (facet: string) => `Constellation view. Items grouped by ${facet.toLowerCase()}, one cluster per value with its count. The Index lists every item with every field.`,
  },
};
